before_install:
#    - sudo apt-get update -qq
    - sudo apt-get install -qq valgrind
os:
     - linux

language: php 

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4

notifications:
  email: false
  irc: "irc.efnet.org#php.yaf"
   
env:
  - REPORT_EXIT_STATUS=1 NO_INTERACTION=1

#Compile
before_script:
    - ./travis/compile.sh

# Run PHPs run-tests.php 
script: TEST_PHP_ARGS="-m --show-mem" make test
